# build environment
FROM node:14.4.0-alpine3.10

# to chage localhost to API_URL
WORKDIR /frontend

COPY package*.json ./
RUN npm ci

COPY . ./
RUN npm run build
RUN npm install -g serve

CMD ["serve", "-s", "build", "-p", "80"]



# # production environment
# FROM nginx:stable-alpine
# # serving react code
# COPY --from=build /frontend/build /usr/share/nginx/html
# # custom nginx config
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
