version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/node_modules:/frontend/node_modules
      - ./frontend:/frontend
    env_file:
      - frontend.env
    depends_on:
      - examples_api
      - custom_data_api

  custom_data_api:
    build:
      context: ./backend
      dockerfile: ./custom_data_api/Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./backend/common:/app/common
      - ./backend/custom_data_api:/app/api
      - ./backend/exampleMat:/app/exampleMat
    env_file:
      - backend.env

  examples_api:
    build:
      context: ./backend
      dockerfile: ./examples_api/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend/common:/app/common
      - ./backend/examples_api:/app/api
      - ./backend/images:/app/images
      - ./backend/generatedData:/app/generatedData
    env_file:
      - backend.env
      - db.env
    depends_on:
      - db

  db:
    image: mysql:8.0.26
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    env_file:
      - db.env
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
volumes:
  mysql:
  mysql_config:
