repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        max_line_length: 100
        in-place: true
        recursive: true
        indent-size: 2
        aggressive: 3
        exclude: "Pipfile*"

  - repo: https://github.com/pycqa/pylint
    rev: v2.9.5
    hooks:
      - id: pylint
        language: system
        files: \.py$
        args:
          - --rcfile=./backend/.pylintrc
