name: CI to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  Frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint frontend
        run: |
          npm run lint
          npm run lint:style
          npm run lint:prettier

      - name: Test frontend
        run: npm run test:CI

  Backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Set up Python 3.9
        uses: actions/checkout@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv run pip install -r requirements.txt

      - name: Lint backend
        run: |
          find . -type f -name "*.py" | xargs pipenv run pylint

      - name: Test backend
        run: export ENVIRONMENT=TEST && pipenv run pytest

  build-images:
    needs:
      - Frontend
      - Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/data-visualization-tool-frontend:latest

      - name: Build and push Backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/data-visualization-tool-backend:latest

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_frontend.outputs.digest }}
          echo ${{ steps.docker_build_backend.outputs.digest }}
