name: CI Pipeline
on: [push]
jobs:
  Frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint frontend
        run: |
          npm run lint
          npm run lint:style

      - name: Test frontend
        run: npm run test:CI

  Backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Set up Python 3.9
        uses: actions/checkout@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv run pip install -r requirements.txt

      - name: Lint backend
        run: |
          find . -type f -name "*.py" | xargs pipenv run pylint

      # - name: Test backend
